// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NeuroGraph.Main.Data;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace Core.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Api.Entities.BiologicalEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Cause")
                        .HasColumnType("text")
                        .HasColumnName("cause");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("kind");

                    b.Property<Guid>("NeuronId")
                        .HasColumnType("uuid")
                        .HasColumnName("neuron_id");

                    b.Property<DateTime>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.HasKey("Id")
                        .HasName("pk_biological_events");

                    b.ToTable("biological_events", (string)null);
                });

            modelBuilder.Entity("Api.Entities.BiologicalSignal", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("FiredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("fired_at");

                    b.Property<float>("Intensity")
                        .HasColumnType("real")
                        .HasColumnName("intensity");

                    b.Property<Guid>("NeuronId")
                        .HasColumnType("uuid")
                        .HasColumnName("neuron_id");

                    b.HasKey("Id")
                        .HasName("pk_biological_signals");

                    b.HasIndex("NeuronId")
                        .HasDatabaseName("ix_biological_signals_neuron_id");

                    b.ToTable("biological_signals", (string)null);
                });

            modelBuilder.Entity("Api.Entities.NeuralConnection", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsExcitatory")
                        .HasColumnType("boolean")
                        .HasColumnName("is_excitatory");

                    b.Property<Guid>("SourceNeuronId")
                        .HasColumnType("uuid")
                        .HasColumnName("source_neuron_id");

                    b.Property<Guid>("TargetNeuronId")
                        .HasColumnType("uuid")
                        .HasColumnName("target_neuron_id");

                    b.Property<double>("Weight")
                        .HasColumnType("double precision")
                        .HasColumnName("weight");

                    b.HasKey("Id")
                        .HasName("pk_neural_connections");

                    b.HasIndex("SourceNeuronId")
                        .HasDatabaseName("ix_neural_connections_source_neuron_id");

                    b.HasIndex("TargetNeuronId")
                        .HasDatabaseName("ix_neural_connections_target_neuron_id");

                    b.ToTable("neural_connections", (string)null);
                });

            modelBuilder.Entity("Api.Entities.Neuron", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTime?>("DiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("died_at");

                    b.Property<double>("Energy")
                        .HasColumnType("double precision")
                        .HasColumnName("energy");

                    b.Property<double>("FiringThreshold")
                        .HasColumnType("double precision")
                        .HasColumnName("firing_threshold");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("label");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("status");

                    b.Property<double>("X")
                        .HasColumnType("double precision")
                        .HasColumnName("x");

                    b.Property<double>("Y")
                        .HasColumnType("double precision")
                        .HasColumnName("y");

                    b.HasKey("Id")
                        .HasName("pk_neurons");

                    b.ToTable("neurons", (string)null);
                });

            modelBuilder.Entity("Api.Entities.NeuronLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Details")
                        .HasColumnType("text")
                        .HasColumnName("details");

                    b.Property<Guid>("NeuronId")
                        .HasColumnType("uuid")
                        .HasColumnName("neuron_id");

                    b.Property<DateTime>("Timestamp")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("timestamp");

                    b.Property<string>("type")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("type");

                    b.HasKey("Id")
                        .HasName("pk_neuron_logs");

                    b.HasIndex("NeuronId")
                        .HasDatabaseName("ix_neuron_logs_neuron_id");

                    b.ToTable("neuron_logs", (string)null);
                });

            modelBuilder.Entity("Api.Entities.Views.BestEventView", b =>
                {
                    b.Property<string>("Cause")
                        .HasColumnType("text")
                        .HasColumnName("cause");

                    b.Property<Guid>("EventId")
                        .HasColumnType("uuid")
                        .HasColumnName("event_id");

                    b.Property<string>("Kind")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("kind");

                    b.Property<Guid>("NeuronId")
                        .HasColumnType("uuid")
                        .HasColumnName("neuron_id");

                    b.Property<DateTime>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.ToTable((string)null);

                    b.ToView("vw_best_events", (string)null);
                });

            modelBuilder.Entity("Api.Entities.Views.NeuronDeathStatsView", b =>
                {
                    b.Property<string>("Cause")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("cause");

                    b.Property<int>("DeathCount")
                        .HasColumnType("integer")
                        .HasColumnName("death_count");

                    b.ToTable((string)null);

                    b.ToView("vw_neuron_death_stats", (string)null);
                });

            modelBuilder.Entity("Api.Entities.Views.NeuronLongevityView", b =>
                {
                    b.Property<int>("EvolutionCount")
                        .HasColumnType("integer")
                        .HasColumnName("evolution_count");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("label");

                    b.Property<int>("LifetimeSeconds")
                        .HasColumnType("integer")
                        .HasColumnName("lifetime_seconds");

                    b.Property<Guid>("NeuronId")
                        .HasColumnType("uuid")
                        .HasColumnName("neuron_id");

                    b.ToTable((string)null);

                    b.ToView("vw_neuron_longevity", (string)null);
                });

            modelBuilder.Entity("Api.Entities.BiologicalSignal", b =>
                {
                    b.HasOne("Api.Entities.Neuron", "Neuron")
                        .WithMany("Signals")
                        .HasForeignKey("NeuronId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_biological_signals_neurons_neuron_id");

                    b.Navigation("Neuron");
                });

            modelBuilder.Entity("Api.Entities.NeuralConnection", b =>
                {
                    b.HasOne("Api.Entities.Neuron", null)
                        .WithMany()
                        .HasForeignKey("SourceNeuronId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_neural_connections_neurons_source_neuron_id");

                    b.HasOne("Api.Entities.Neuron", null)
                        .WithMany()
                        .HasForeignKey("TargetNeuronId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_neural_connections_neurons_target_neuron_id");
                });

            modelBuilder.Entity("Api.Entities.NeuronLog", b =>
                {
                    b.HasOne("Api.Entities.Neuron", "Neuron")
                        .WithMany("Logs")
                        .HasForeignKey("NeuronId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_neuron_logs_neurons_neuron_id");

                    b.Navigation("Neuron");
                });

            modelBuilder.Entity("Api.Entities.Neuron", b =>
                {
                    b.Navigation("Logs");

                    b.Navigation("Signals");
                });
#pragma warning restore 612, 618
        }
    }
}
