// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using NeuroGraph.Infrastructure.Persistence;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace NeuroGraph.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(NeuroGraphDbContext))]
    [Migration("20260602222959_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.27")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("NeuroGraph.Domain.Entities.BiologicalEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("description");

                    b.Property<Guid?>("NeuronId")
                        .HasColumnType("uuid")
                        .HasColumnName("neuron_id");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at");

                    b.Property<double>("OutcomeScore")
                        .HasColumnType("double precision")
                        .HasColumnName("outcome_score");

                    b.Property<int>("Type")
                        .HasColumnType("integer")
                        .HasColumnName("type");

                    b.HasKey("Id");

                    b.HasIndex("NeuronId");

                    b.HasIndex("OccurredAt");

                    b.HasIndex("Type");

                    b.ToTable("biological_events", (string)null);
                });

            modelBuilder.Entity("NeuroGraph.Domain.Entities.BiologicalSignal", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<double>("Intensity")
                        .HasColumnType("double precision")
                        .HasColumnName("intensity");

                    b.Property<Guid>("NeuronId")
                        .HasColumnType("uuid")
                        .HasColumnName("neuron_id");

                    b.Property<int>("Type")
                        .HasColumnType("integer")
                        .HasColumnName("type");

                    b.HasKey("Id");

                    b.HasIndex("NeuronId");

                    b.ToTable("biological_signals", (string)null);
                });

            modelBuilder.Entity("NeuroGraph.Domain.Entities.NeuralConnection", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<bool>("IsActive")
                        .HasColumnType("boolean")
                        .HasColumnName("is_active");

                    b.Property<Guid>("SourceNeuronId")
                        .HasColumnType("uuid")
                        .HasColumnName("source_neuron_id");

                    b.Property<Guid>("TargetNeuronId")
                        .HasColumnType("uuid")
                        .HasColumnName("target_neuron_id");

                    b.Property<double>("Weight")
                        .HasColumnType("double precision")
                        .HasColumnName("weight");

                    b.HasKey("Id");

                    b.HasIndex("TargetNeuronId");

                    b.HasIndex("SourceNeuronId", "TargetNeuronId")
                        .IsUnique();

                    b.ToTable("neural_connections", (string)null);
                });

            modelBuilder.Entity("NeuroGraph.Domain.Entities.Neuron", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<DateTimeOffset?>("DiedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("died_at");

                    b.Property<int>("FireCount")
                        .HasColumnType("integer")
                        .HasColumnName("fire_count");

                    b.Property<int>("Generation")
                        .HasColumnType("integer")
                        .HasColumnName("generation");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("character varying(120)")
                        .HasColumnName("label");

                    b.Property<DateTimeOffset?>("LastFiredAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("last_fired_at");

                    b.Property<double>("MembranePotential")
                        .HasColumnType("double precision")
                        .HasColumnName("membrane_potential");

                    b.Property<double>("PositionX")
                        .HasColumnType("double precision")
                        .HasColumnName("position_x");

                    b.Property<double>("PositionY")
                        .HasColumnType("double precision")
                        .HasColumnName("position_y");

                    b.Property<int>("Status")
                        .HasColumnType("integer")
                        .HasColumnName("status");

                    b.Property<double>("Threshold")
                        .HasColumnType("double precision")
                        .HasColumnName("threshold");

                    b.HasKey("Id");

                    b.HasIndex("Status");

                    b.ToTable("neurons", (string)null);
                });

            modelBuilder.Entity("NeuroGraph.Domain.Entities.NeuronLog", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("action");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<Guid>("NeuronId")
                        .HasColumnType("uuid")
                        .HasColumnName("neuron_id");

                    b.Property<double>("PotentialSnapshot")
                        .HasColumnType("double precision")
                        .HasColumnName("potential_snapshot");

                    b.HasKey("Id");

                    b.HasIndex("NeuronId");

                    b.ToTable("neurons_logs", (string)null);
                });

            modelBuilder.Entity("NeuroGraph.Domain.Entities.BiologicalEvent", b =>
                {
                    b.HasOne("NeuroGraph.Domain.Entities.Neuron", "Neuron")
                        .WithMany("Events")
                        .HasForeignKey("NeuronId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Neuron");
                });

            modelBuilder.Entity("NeuroGraph.Domain.Entities.BiologicalSignal", b =>
                {
                    b.HasOne("NeuroGraph.Domain.Entities.Neuron", "Neuron")
                        .WithMany("Signals")
                        .HasForeignKey("NeuronId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Neuron");
                });

            modelBuilder.Entity("NeuroGraph.Domain.Entities.NeuralConnection", b =>
                {
                    b.HasOne("NeuroGraph.Domain.Entities.Neuron", "Source")
                        .WithMany("OutgoingConnections")
                        .HasForeignKey("SourceNeuronId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("NeuroGraph.Domain.Entities.Neuron", "Target")
                        .WithMany("IncomingConnections")
                        .HasForeignKey("TargetNeuronId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Source");

                    b.Navigation("Target");
                });

            modelBuilder.Entity("NeuroGraph.Domain.Entities.NeuronLog", b =>
                {
                    b.HasOne("NeuroGraph.Domain.Entities.Neuron", "Neuron")
                        .WithMany("Logs")
                        .HasForeignKey("NeuronId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Neuron");
                });

            modelBuilder.Entity("NeuroGraph.Domain.Entities.Neuron", b =>
                {
                    b.Navigation("Events");

                    b.Navigation("IncomingConnections");

                    b.Navigation("Logs");

                    b.Navigation("OutgoingConnections");

                    b.Navigation("Signals");
                });
#pragma warning restore 612, 618
        }
    }
}
